name: Shivaraj
favicon: null
layout_spectrum: 0.043733742786571383
typography_spectrum: 0.5600483773741871
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5933660380542278
  lightness: 0.3135534171015024
  saturation: 0.5212528991978616
  rhythmicContrast: 0.047689184779301286
purpose: []
